### ISSUE TITLE
Darwin Core export: four pseudo-duplicated fields

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/ala-downloads#17]
basisOfRecord, class, dcterms:bibliographicCitation and specificEpithet each appear twice among the 187 fields in a Darwin Core TSV export. These are pseudo-duplicates, because in the two ca 500000-records sets I downloaded on 3 August 2017, the two "class", "dcterms:bibliographicCitation" and "specificEpithet" fields had very different content, i.e., wrong values in one of the pseudo-replicates.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#341
