### ISSUE TITLE
Provide citations with downloads for records

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-downloads#3]
Provide citations with downloads for records. Currently the downloaded zip doesnt contain this.

**Comment by nickdos** [comment]
This is now present - as citations.csv

But it could do with some enhancing. @M-Nicholls has some ideas about including a full citation string and to include both the original URL to the search as well auto-inserting the date for "access on 2016-03-18".

**Comment by M-Nicholls** [comment]
done- full query and citation string now included
